### ISSUE TITLE
Envie seus materiais

### ISSUE THREAD

**Issue by tiagoboeing** [computacaoUnisul/biblioteca-da-computacao-materiais#1]
## Basta comentar esta issue ou fazer um fork devolvendo as alterações.
Se possível, preencha os seguintes dados:
- Professor
- Matéria
- Semestre

> não esqueça de anexar os arquivos

**Comment by VBviniciusVB** [comment]
Charbel - Compiladores - 8° Semestre
Carlos - Redes - 6° Semestre

[Uploading Trabalhos Rede e Compiladores.zip…]()

**Comment by VBviniciusVB** [comment]
Charbel - Compiladores - 8° Semestre
Carlos - Redes de Computadores - 6° Semestre

[Trabalhos Rede e Compiladores.zip](https://github.com/computacaoUnisul/biblioteca-da-computacao-materiais/files/4135478/Trabalhos.Rede.e.Compiladores.zip)

**Comment by tiagoboeing** [comment]
> Charbel - Compiladores - 8° Semestre
> Carlos - Redes de Computadores - 6° Semestre
> 
> [Trabalhos Rede e Compiladores.zip](https://github.com/computacaoUnisul/biblioteca-da-computacao-materiais/files/4135478/Trabalhos.Rede.e.Compiladores.zip)

Materiais cadastrados:
- Compiladores: ab4fc84027a48d0239e19c3d156ade39ded649b8
- Trabalho final de Redes I: 7740f5ba71a911f92fa86e9a4ebb4ba0dbc53802

**Comment by rocha-rafael** [comment]
Professor: Clávison
Matéria: Programação para Web
Semestre: 5°

Anexo as avaliações e as suas resoluções.

[Prova_2_-_API.docx](https://github.com/computacaoUnisul/biblioteca-da-computacao-materiais/files/4988108/Prova_2_-_API.docx)
[Prova_1_-_flutter.docx](https://github.com/computacaoUnisul/biblioteca-da-computacao-materiais/files/4988109/Prova_1_-_flutter.docx)
[Prova 1.zip](https://github.com/computacaoUnisul/biblioteca-da-computacao-materiais/files/4988126/Prova.1.zip)
[Prova 2.zip](https://github.com/computacaoUnisul/biblioteca-da-computacao-materiais/files/4988127/Prova.2.zip)

**Comment by rocha-rafael** [comment]
Professor: Paulo Rufino
Matéria: Integrais
Semestre: 5°

Anexo as avaliações e as suas resoluções.

[prova 3 questões.pdf](https://github.com/computacaoUnisul/biblioteca-da-computacao-materiais/files/4988175/prova.3.questoes.pdf)
[prova 2 questões.pdf](https://github.com/computacaoUnisul/biblioteca-da-computacao-materiais/files/4988176/prova.2.questoes.pdf)
[prova 1 questões.pdf](https://github.com/computacaoUnisul/biblioteca-da-computacao-materiais/files/4988177/prova.1.questoes.pdf)


[PROVA_3 peso 5.pdf](https://github.com/computacaoUnisul/biblioteca-da-computacao-materiais/files/4988140/PROVA_3.peso.5.pdf)
[Prova_2.pdf](https://github.com/computacaoUnisul/biblioteca-da-computacao-materiais/files/4988141/Prova_2.pdf)
[Prova_1.pdf](https://github.com/computacaoUnisul/biblioteca-da-computacao-materiais/files/4988142/Prova_1.pdf)
[desafio prova 3 - peso 5.pdf](https://github.com/computacaoUnisul/biblioteca-da-computacao-materiais/files/4988148/desafio.prova.3.-.peso.5.pdf)

**Comment by luizeduardosguimaraes** [comment]
Professora: Ana Luísa Mülbert
Disciplina: CIBERCULTURA E PRÁTICA PROFISSIONAL EM TECNOLOGIA DA INFORMAÇÃO (virtual, 2020/B)
Avaliação a Distância 1
Avaliação Presencial(Virtual, por conta do Coronavírus) não teve como baixar, foi um formulário dentro do MINHA UNISUL
[LUIZ_EDUARDO_DE_SOUZA_GUIMARAES-[67784-901-1-943235]CIBERCULTURA-2020-2.docx](https://github.com/computacaoUnisul/biblioteca-da-computacao-materiais/files/5568469/LUIZ_EDUARDO_DE_SOUZA_GUIMARAES-.67784-901-1-943235.CIBERCULTURA-2020-2.docx)

**Comment by luizeduardosguimaraes** [comment]
Disciplina: Aplicação de Banco de Dados
Semestre: 2020/B
Professor: Luciano Savio
Avaliação 1
[LUIZ_EDUARDO_DE_SOUZA_GUIMARAES-[65588-901-2-924460]79109-65588bd_apl_aula07_av1.pdf](https://github.com/computacaoUnisul/biblioteca-da-computacao-materiais/files/5568512/LUIZ_EDUARDO_DE_SOUZA_GUIMARAES-.65588-901-2-924460.79109-65588bd_apl_aula07_av1.pdf)
[LUIZ_EDUARDO_DE_SOUZA_GUIMARAES-[65588-901-2-924460]79109-65588bd_apl_aula07_av1.pdf](https://github.com/computacaoUnisul/biblioteca-da-computacao-materiais/files/5568513/LUIZ_EDUARDO_DE_SOUZA_GUIMARAES-.65588-901-2-924460.79109-65588bd_apl_aula07_av1.pdf)

**Comment by tiagoboeing** [comment]
> Professora: Ana Luísa Mülbert
> Disciplina: CIBERCULTURA E PRÁTICA PROFISSIONAL EM TECNOLOGIA DA INFORMAÇÃO (virtual, 2020/B)
> Avaliação a Distância 1
> Avaliação Presencial(Virtual, por conta do Coronavírus) não teve como baixar, foi um formulário dentro do MINHA UNISUL
> [LUIZ_EDUARDO_DE_SOUZA_GUIMARAES-[67784-901-1-943235]CIBERCULTURA-2020-2.docx](https://github.com/computacaoUnisul/biblioteca-da-computacao-materiais/files/5568469/LUIZ_EDUARDO_DE_SOUZA_GUIMARAES-.67784-901-1-943235.CIBERCULTURA-2020-2.docx)



> Disciplina: Aplicação de Banco de Dados
> Semestre: 2020/B
> Professor: Luciano Savio
> Avaliação 1
> [LUIZ_EDUARDO_DE_SOUZA_GUIMARAES-[65588-901-2-924460]79109-65588bd_apl_aula07_av1.pdf](https://github.com/computacaoUnisul/biblioteca-da-computacao-materiais/files/5568512/LUIZ_EDUARDO_DE_SOUZA_GUIMARAES-.65588-901-2-924460.79109-65588bd_apl_aula07_av1.pdf)
> [LUIZ_EDUARDO_DE_SOUZA_GUIMARAES-[65588-901-2-924460]79109-65588bd_apl_aula07_av1.pdf](https://github.com/computacaoUnisul/biblioteca-da-computacao-materiais/files/5568513/LUIZ_EDUARDO_DE_SOUZA_GUIMARAES-.65588-901-2-924460.79109-65588bd_apl_aula07_av1.pdf)

Ambos adicionados em https://github.com/computacaoUnisul/biblioteca-da-computacao-materiais/commit/8209aaeb79b849a497763c286bdcdaf10822bbc8

**Comment by tiagoboeing** [comment]
> Professor: Clávison
> Matéria: Programação para Web
> Semestre: 5°
> 
> Anexo as avaliações e as suas resoluções.
> 
> [Prova_2_-_API.docx](https://github.com/computacaoUnisul/biblioteca-da-computacao-materiais/files/4988108/Prova_2_-_API.docx)
> [Prova_1_-_flutter.docx](https://github.com/computacaoUnisul/biblioteca-da-computacao-materiais/files/4988109/Prova_1_-_flutter.docx)
> [Prova 1.zip](https://github.com/computacaoUnisul/biblioteca-da-computacao-materiais/files/4988126/Prova.1.zip)
> [Prova 2.zip](https://github.com/computacaoUnisul/biblioteca-da-computacao-materiais/files/4988127/Prova.2.zip)

Adicionado em https://github.com/computacaoUnisul/biblioteca-da-computacao-materiais/commit/9497b765926ffeb4701783375d72eb8d01af0987

**Comment by tiagoboeing** [comment]
> : Paulo Rufino
> Matéria: Integrais
> Semestre: 5°

Adicionado em https://github.com/computacaoUnisul/biblioteca-da-computacao-materiais/commit/e317fbbc5912c2dfbf3de4dea07961462650102a

**Comment by tiagoboeing** [comment]
À partir de agora para enviar materias faça fork do repositório e devolva as alterações por meio de pull requests ou [abra uma issue específica](https://github.com/computacaoUnisul/biblioteca-da-computacao-materiais/issues/new) solicitando a inclusão dos materiais e enviando os arquivos.
