### ISSUE TITLE
Tradução de Linguagens de Programação / 2020-1

### ISSUE THREAD

**Issue by luizeduardosguimaraes** [computacaoUnisul/biblioteca-da-computacao-materiais#11]
- Professor: Luciano
- Matéria: Tradução de Linguagens de Programação
[LUIZ_EDUARDO_DE_SOUZA_GUIMARAES-[65591-901-1-924460]78892-65591Av1_20202_Compiladores.docx](https://github.com/computacaoUnisul/biblioteca-da-computacao-materiais/files/5631096/LUIZ_EDUARDO_DE_SOUZA_GUIMARAES-.65591-901-1-924460.78892-65591Av1_20202_Compiladores.docx)
 (Compiladores)
- Semestre: 2020/1

> Não esqueça de realizar upload do (s) arquivo (s).

**Comment by tiagoboeing** [comment]
Adicionado no commit https://github.com/computacaoUnisul/biblioteca-da-computacao-materiais/commit/021c79b2a40e90d72df42d7fe0d5d721a485cd83
