### ISSUE TITLE
Compiladores Av2

### ISSUE THREAD

**Issue by luizeduardosguimaraes** [computacaoUnisul/biblioteca-da-computacao-materiais#12]
Avaliação 02
[[81867-65591]Av2_20202.pdf](https://github.com/computacaoUnisul/biblioteca-da-computacao-materiais/files/5639996/81867-65591.Av2_20202.pdf)

Favor ajustar ali pra ficar junto da AV 01

**Comment by tiagoboeing** [comment]
Adicionado no commit https://github.com/computacaoUnisul/biblioteca-da-computacao-materiais/commit/d426e201baab9e49cd652ed95f15fecc8d04b401
