### ISSUE TITLE
Bd aplicado prova 3

### ISSUE THREAD

**Issue by luizeduardosguimaraes** [computacaoUnisul/biblioteca-da-computacao-materiais#5]
![IMG-20191122-WA0020](https://user-images.githubusercontent.com/36969037/69470880-806bb380-0d78-11ea-8abc-d33f076a5c9b.jpg)

**Comment by tiagoboeing** [comment]
@luizeduardosguimaraes material adicionado e issue sendo fechada, caso necessário poderá ser reaberta.
