### ISSUE TITLE
Avaliação Presencial Cibercultura

### ISSUE THREAD

**Issue by luizeduardosguimaraes** [computacaoUnisul/biblioteca-da-computacao-materiais#8]
Disciplina: Cibercultura

Só acrescentar lá na pasta da matéria

Avaliação Presencial(Virtual por conta do coronavírus). Consegui pegar e printar todas as questões e fiz a junção em forma de arquivo. 
[AV2_AP_Cibercultura_Luiz_Eduardo_de_Souza_Guimaraes.pdf](https://github.com/computacaoUnisul/biblioteca-da-computacao-materiais/files/5582795/AV2_AP_Cibercultura_Luiz_Eduardo_de_Souza_Guimaraes.pdf)

**Comment by tiagoboeing** [comment]
Adicionado!
